//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※近日実装予定.
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知しない.
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未実装).
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知設定.
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Windows 8 以降).
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一覧を生成しています....
        /// </summary>
        public static string CommonCatalog_GeneratingList {
            get {
                return ResourceManager.GetString("CommonCatalog_GeneratingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示の更新.
        /// </summary>
        public static string CommonCatalog_Refresh {
            get {
                return ResourceManager.GetString("CommonCatalog_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to これはテスト通知です。.
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テスト.
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造ドック.
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成！.
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造中の艦名をネタバレする.
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示設定.
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックされています.
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠第 {0} ドックでの{1}の建造が完了しました。.
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了.
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了時に通知を表示する.
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドックごとに個別に設定する.
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造中の艦.
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成時刻.
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了まで.
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征.
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征に出ていません。.
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」が遠征から帰投しました。.
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征完了.
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征帰投時に通知を表示する.
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Fleet Settings.
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊.
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空戦力.
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均.
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速艦隊.
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速艦隊.
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計.
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵能力.
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司令部.
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修資材:.
        /// </summary>
        public static string Homeport_ImprovementMaterial {
            get {
                return ResourceManager.GetString("Homeport_ImprovementMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速建造材:.
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速修復材:.
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保有装備:.
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属艦娘:.
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総合.
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この艦隊は遠征中です。.
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  完了時刻:.
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  帰投まで:.
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss}.
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に入渠中の艦娘がいます。.
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労中の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に{0}がいます。.
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃可能！.
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未補給の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再出撃までの目安: .
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ・.
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中破以上の艦娘.
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a ship is in critical condition!.
        /// </summary>
        public static string Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Ship Warning.
        /// </summary>
        public static string Notifications_CriticalCondition_Title {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復完了.
        /// </summary>
        public static string Notifications_MoraleRestored {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「{0}」に編成されている艦娘の疲労が回復しました。.
        /// </summary>
        public static string Notifications_MoraleRestored_Details {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データ.
        /// </summary>
        public static string Overview_Data {
            get {
                return ResourceManager.GetString("Overview_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備一覧.
        /// </summary>
        public static string Overview_EquipmentList {
            get {
                return ResourceManager.GetString("Overview_EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘一覧.
        /// </summary>
        public static string Overview_ShipList {
            get {
                return ResourceManager.GetString("Overview_ShipList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務画面の全ページにアクセスしてください。.
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  50 % .
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  80 % .
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  完了 .
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未取得の任務).
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在遂行中の任務.
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デイリー任務.
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マンスリー任務.
        /// </summary>
        public static string Quests_Monthly {
            get {
                return ResourceManager.GetString("Quests_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 発生中の任務はありません.
        /// </summary>
        public static string Quests_NoQuest {
            get {
                return ResourceManager.GetString("Quests_NoQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。.
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。.
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィークリー任務.
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大将.
        /// </summary>
        public static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大佐.
        /// </summary>
        public static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中佐.
        /// </summary>
        public static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中堅少佐.
        /// </summary>
        public static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少佐.
        /// </summary>
        public static string Rank_Lieutenant_Commander {
            get {
                return ResourceManager.GetString("Rank_Lieutenant_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元帥.
        /// </summary>
        public static string Rank_Marshal_Admiral {
            get {
                return ResourceManager.GetString("Rank_Marshal_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米中佐.
        /// </summary>
        public static string Rank_Novice_Commander {
            get {
                return ResourceManager.GetString("Rank_Novice_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米少佐.
        /// </summary>
        public static string Rank_Novice_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Novice_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少将.
        /// </summary>
        public static string Rank_Rear_Admiral {
            get {
                return ResourceManager.GetString("Rank_Rear_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中将.
        /// </summary>
        public static string Rank_Vice_Admiral {
            get {
                return ResourceManager.GetString("Rank_Vice_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠ドック.
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠第 {0} ドックでの「{1}」の整備が完了しました。.
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整備完了.
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整備完了時に通知を表示する.
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドックごとに個別に設定する.
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠中の艦.
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成時刻.
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了まで.
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未使用.
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットの保存に失敗しました: .
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットを保存しました: .
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザー操作.
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム倍率を 100 % に戻す.
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (表示).
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ゲームのページから移動します。ご注意ください.
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知音を設定.
        /// </summary>
        public static string Settings_CustomSound {
            get {
                return ResourceManager.GetString("Settings_CustomSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボリューム.
        /// </summary>
        public static string Settings_CustomSound_Volume {
            get {
                return ResourceManager.GetString("Settings_CustomSound_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示設定.
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string Settings_Flash {
            get {
                return ResourceManager.GetString("Settings_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This works with DMM.com. OSAPI, and API links now!
        ///[You must reload the game for the changes to take affect.].
        /// </summary>
        public static string Settings_Flash_Message {
            get {
                return ResourceManager.GetString("Settings_Flash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Flash Quality:.
        /// </summary>
        public static string Settings_Flash_Quality {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best: Anti-Aliasing enabled on all images (Slowest)
        ///High: Default.
        ///Auto-High: Automatically lowers quality when needed.
        ///Medium: Average Performance
        ///AutoLow: Will emphasize speed when needed
        ///Low: Performance over quality. Ugliest setting..
        /// </summary>
        public static string Settings_Flash_Quality_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Flash Window:.
        /// </summary>
        public static string Settings_Flash_Window {
            get {
                return ResourceManager.GetString("Settings_Flash_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opaque: Default (Old IE has no HW accel)
        ///Direct: Fastest rendering speed (HW accel)
        ///GPU: Slow! GPU optimization for tablets..
        /// </summary>
        public static string Settings_Flash_Window_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Window_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ.
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ・建造・開発ログを記録する.
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネットワーク.
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Password {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロキシ サーバーにユーザー名とパスワードが必要.
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Required {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名.
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Username {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通信設定.
        /// </summary>
        public static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下のプラグインを使用して通知されます。.
        /// </summary>
        public static string Settings_Notifications_ActiveNotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_ActiveNotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知を早める：.
        /// </summary>
        public static string Settings_Notifications_AheadOfTime {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これ本体の仕様により、最大 1 分間短縮できます。サーバー時刻とのずれを加味し、40 ～ 50 秒に設定することを推奨します。.
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Seconds {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了時に通知する.
        /// </summary>
        public static string Settings_Notifications_Construction_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Construction_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリティカル時に通知する.
        /// </summary>
        public static string Settings_Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Settings_Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征帰投時に通知する.
        /// </summary>
        public static string Settings_Notifications_Expeditions_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Expeditions_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に編成されている艦娘の疲労が回復したら通知する.
        /// </summary>
        public static string Settings_Notifications_FleetsMorale {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に編成されているすべて艦娘のコンディション値が上記の値以上になったときに通知されます。コンディション値は 3 分間で 3 ずつ回復しますが、KanColleViewer 実装の仕様により、通知タイミングは数秒 ～ 最大 3 分程度遅れる可能性があること予めご了承ください。.
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※[動作設定] &gt; [出撃コンディション] から設定できます。.
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Reference {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再出撃可能とするコンディション値.
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Threshold {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知設定.
        /// </summary>
        public static string Settings_Notifications_NotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_NotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠完了時に通知する.
        /// </summary>
        public static string Settings_Notifications_Repair_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Repair_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作設定.
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦上偵察機.
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彩雲、二式艦上偵察機.
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (偵察機 × 2) + (電探) + √(装備込みの艦隊索敵値合計 - 偵察機 - 電探).
        /// </summary>
        public static string Settings_Operation_LoS_New {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備による索敵値が重要とされる場合の計算方法 (推定).
        /// </summary>
        public static string Settings_Operation_LoS_New_Desc {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偵察機.
        /// </summary>
        public static string Settings_Operation_LoS_Recon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水上爆撃機.
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞雲、瑞雲(六三四空)、試製晴嵐.
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水上偵察機.
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 零式水上偵察機、零式水上観測機、九八式水上偵察機(夜偵).
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘と装備の索敵値の単純な合計.
        /// </summary>
        public static string Settings_Operation_LoS_Simple {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanColleViewer での従来の計算方法.
        /// </summary>
        public static string Settings_Operation_LoS_Simple_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊の索敵値の算出に使用する計算式は、以下を使用する.
        /// </summary>
        public static string Settings_Operation_LoS_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵値計算.
        /// </summary>
        public static string Settings_Operation_LoSCalculation {
            get {
                return ResourceManager.GetString("Settings_Operation_LoSCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃コンディション.
        /// </summary>
        public static string Settings_Operation_SortieCondition {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※通常は、間宮アイコンが消灯する 40 か、自然回復上限の 49 に設定します。.
        /// </summary>
        public static string Settings_Operation_SortieCondition_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊内の全艦のコンディションが次の数値以上になったとき、出撃可能と判断する.
        /// </summary>
        public static string Settings_Operation_SortieCondition_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロキシ設定.
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通信にプロキシ サーバーを使用する.
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL 接続時もプロキシサーバーを使用する.
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバー.
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート.
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット.
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショットの保存先を指定.
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先フォルダーのパス.
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像形式.
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダーを開く.
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Settings_Translations {
            get {
                return ResourceManager.GetString("Settings_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append untranslated items to the translation files?.
        /// </summary>
        public static string Settings_Translations_Add_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Add_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate game items, ships, and quests to selected language?.
        /// </summary>
        public static string Settings_Translations_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI設定.
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイコンを利用する.
        /// </summary>
        public static string Settings_UI_Icon {
            get {
                return ResourceManager.GetString("Settings_UI_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート.
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update translations on startup.
        /// </summary>
        public static string Settings_Updates_AutoUpdateTrans {
            get {
                return ResourceManager.GetString("Settings_Updates_AutoUpdateTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for the latest program and translation versions.
        /// </summary>
        public static string Settings_Updates_CheckUpdateButn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdateButn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version of KCV and translate..
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently.
        /// </summary>
        public static string Settings_Updates_CurrentVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force download.
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all translatations without check version!.
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Latest KCV.
        /// </summary>
        public static string Settings_Updates_GetKCVBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a link to the latest version of KCV found here..
        /// </summary>
        public static string Settings_Updates_GetKCVBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Settings_Updates_OnlineVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_OnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート設定.
        /// </summary>
        public static string Settings_Updates_Option {
            get {
                return ResourceManager.GetString("Settings_Updates_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string Settings_Updates_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Translations.
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads new translations.
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン情報.
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ設定.
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウを常に最前面に表示する.
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ操作.
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウをモニターの左端に寄せる.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 インチタブレット (800 x 1280) 用.
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠: {0}.
        /// </summary>
        public static string Ship_RepairDockToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairDockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 施設: {0}.
        /// </summary>
        public static string Ship_RepairFacilityToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairFacilityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠中.
        /// </summary>
        public static string Ship_Repairing {
            get {
                return ResourceManager.GetString("Ship_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        public static string ShipCatalog_All {
            get {
                return ResourceManager.GetString("ShipCatalog_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        public static string ShipCatalog_AntiAir {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        public static string ShipCatalog_AntiSub {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        public static string ShipCatalog_Armor {
            get {
                return ResourceManager.GetString("ShipCatalog_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備.
        /// </summary>
        public static string ShipCatalog_Equips {
            get {
                return ResourceManager.GetString("ShipCatalog_Equips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避.
        /// </summary>
        public static string ShipCatalog_Evasion {
            get {
                return ResourceManager.GetString("ShipCatalog_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征中の艦を除外する.
        /// </summary>
        public static string ShipCatalog_ExcludeShipOnExpedition {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShipOnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦種を除く！.
        /// </summary>
        public static string ShipCatalog_ExcludeShiptype {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShiptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征.
        /// </summary>
        public static string ShipCatalog_Expedition {
            get {
                return ResourceManager.GetString("ShipCatalog_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        public static string ShipCatalog_Fast {
            get {
                return ResourceManager.GetString("ShipCatalog_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター設定.
        /// </summary>
        public static string ShipCatalog_FilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        public static string ShipCatalog_Firepower {
            get {
                return ResourceManager.GetString("ShipCatalog_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string ShipCatalog_Level {
            get {
                return ResourceManager.GetString("ShipCatalog_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv.1.
        /// </summary>
        public static string ShipCatalog_Level1 {
            get {
                return ResourceManager.GetString("ShipCatalog_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv.2 以上.
        /// </summary>
        public static string ShipCatalog_Level2Up {
            get {
                return ResourceManager.GetString("ShipCatalog_Level2Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロック.
        /// </summary>
        public static string ShipCatalog_Lock {
            get {
                return ResourceManager.GetString("ShipCatalog_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックしている.
        /// </summary>
        public static string ShipCatalog_Locked {
            get {
                return ResourceManager.GetString("ShipCatalog_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        public static string ShipCatalog_LoS {
            get {
                return ResourceManager.GetString("ShipCatalog_LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運.
        /// </summary>
        public static string ShipCatalog_Luck {
            get {
                return ResourceManager.GetString("ShipCatalog_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 近代化改修.
        /// </summary>
        public static string ShipCatalog_Modernization {
            get {
                return ResourceManager.GetString("ShipCatalog_Modernization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修完了.
        /// </summary>
        public static string ShipCatalog_ModernizationComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修未完.
        /// </summary>
        public static string ShipCatalog_ModernizationIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦名.
        /// </summary>
        public static string ShipCatalog_Name {
            get {
                return ResourceManager.GetString("ShipCatalog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL 作戦参加済み.
        /// </summary>
        public static string ShipCatalog_Operation_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MI 作戦参加済み.
        /// </summary>
        public static string ShipCatalog_Operation_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作戦出撃なし.
        /// </summary>
        public static string ShipCatalog_Operation_NeitherALnorMI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_NeitherALnorMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造.
        /// </summary>
        public static string ShipCatalog_Remodel {
            get {
                return ResourceManager.GetString("ShipCatalog_Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造完了.
        /// </summary>
        public static string ShipCatalog_RemodelComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造未完.
        /// </summary>
        public static string ShipCatalog_RemodelIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター設定リセット.
        /// </summary>
        public static string ShipCatalog_ResetFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_ResetFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター設定セーブ.
        /// </summary>
        public static string ShipCatalog_SaveFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_SaveFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて選択.
        /// </summary>
        public static string ShipCatalog_SelectAll {
            get {
                return ResourceManager.GetString("ShipCatalog_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦種.
        /// </summary>
        public static string ShipCatalog_ShipType {
            get {
                return ResourceManager.GetString("ShipCatalog_ShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加の統計を示す.
        /// </summary>
        public static string ShipCatalog_ShowAdditionalShipStats {
            get {
                return ResourceManager.GetString("ShipCatalog_ShowAdditionalShipStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速.
        /// </summary>
        public static string ShipCatalog_Slow {
            get {
                return ResourceManager.GetString("ShipCatalog_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃海域.
        /// </summary>
        public static string ShipCatalog_SortieWaters {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL 作戦.
        /// </summary>
        public static string ShipCatalog_SortieWaters_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MI 作戦.
        /// </summary>
        public static string ShipCatalog_SortieWaters_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速力.
        /// </summary>
        public static string ShipCatalog_Speed {
            get {
                return ResourceManager.GetString("ShipCatalog_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        public static string ShipCatalog_Torpedo {
            get {
                return ResourceManager.GetString("ShipCatalog_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロックしていない.
        /// </summary>
        public static string ShipCatalog_Unlocked {
            get {
                return ResourceManager.GetString("ShipCatalog_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        public static string Shipyard {
            get {
                return ResourceManager.GetString("Shipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造.
        /// </summary>
        public static string Shipyard_ConstructionDock {
            get {
                return ResourceManager.GetString("Shipyard_ConstructionDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備開発・ドロップ.
        /// </summary>
        public static string Shipyard_Development {
            get {
                return ResourceManager.GetString("Shipyard_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗.
        /// </summary>
        public static string Shipyard_Development_Result_Failure {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果なし.
        /// </summary>
        public static string Shipyard_Development_Result_None {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Shipyard_Development_Result_Success {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ.
        /// </summary>
        public static string Shipyard_Drop {
            get {
                return ResourceManager.GetString("Shipyard_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠.
        /// </summary>
        public static string Shipyard_RepairDock {
            get {
                return ResourceManager.GetString("Shipyard_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備名.
        /// </summary>
        public static string SlotItemCatalog_EqipName {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EqipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備している艦娘.
        /// </summary>
        public static string SlotItemCatalog_EquippedShipGirls {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EquippedShipGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 余り.
        /// </summary>
        public static string SlotItemCatalog_Extra {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所持数.
        /// </summary>
        public static string SlotItemCatalog_Owned {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 統計.
        /// </summary>
        public static string SlotItemCatalog_Stats {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュの削除.
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュを削除しました.
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。.
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Cookie Region.
        /// </summary>
        public static string StartContent_SetRegionCookieButton {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie has been set.
        /// </summary>
        public static string StartContent_SetRegionCookieMessage {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure DMM.com is set to Japanese (日本語).
        /// </summary>
        public static string StartContent_SetRegionCookieToolTip {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ようこそ.
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破した艦娘がいます！！！.
        /// </summary>
        public static string StateDetail_CriticalDamage {
            get {
                return ResourceManager.GetString("StateDetail_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に艦娘が編成されていません。.
        /// </summary>
        public static string StateDetail_EmptyFleet {
            get {
                return ResourceManager.GetString("StateDetail_EmptyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃可能！.
        /// </summary>
        public static string StateDetail_IsReady {
            get {
                return ResourceManager.GetString("StateDetail_IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復済み.
        /// </summary>
        public static string StateDetail_MoraleRecovering {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復まで.
        /// </summary>
        public static string StateDetail_MoraleRecoveryTimer {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecoveryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征中.
        /// </summary>
        public static string StateDetail_OnExpedition {
            get {
                return ResourceManager.GetString("StateDetail_OnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊は出撃中です！.
        /// </summary>
        public static string StateDetail_OnSortie {
            get {
                return ResourceManager.GetString("StateDetail_OnSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に入渠中の艦娘がいます。.
        /// </summary>
        public static string StateDetail_Repairing {
            get {
                return ResourceManager.GetString("StateDetail_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊に未補給の艦娘がいます。.
        /// </summary>
        public static string StateDetail_ShortSupply {
            get {
                return ResourceManager.GetString("StateDetail_ShortSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中.
        /// </summary>
        public static string Stats_Accuracy {
            get {
                return ResourceManager.GetString("Stats_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        public static string Stats_AntiAir {
            get {
                return ResourceManager.GetString("Stats_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        public static string Stats_AntiSub {
            get {
                return ResourceManager.GetString("Stats_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        public static string Stats_Armor {
            get {
                return ResourceManager.GetString("Stats_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射程.
        /// </summary>
        public static string Stats_AttackRange {
            get {
                return ResourceManager.GetString("Stats_AttackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆装.
        /// </summary>
        public static string Stats_DiveBomb {
            get {
                return ResourceManager.GetString("Stats_DiveBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避.
        /// </summary>
        public static string Stats_Evasion {
            get {
                return ResourceManager.GetString("Stats_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        public static string Stats_Firepower {
            get {
                return ResourceManager.GetString("Stats_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耐久.
        /// </summary>
        public static string Stats_Health {
            get {
                return ResourceManager.GetString("Stats_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運.
        /// </summary>
        public static string Stats_Luck {
            get {
                return ResourceManager.GetString("Stats_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        public static string Stats_SightRange {
            get {
                return ResourceManager.GetString("Stats_SightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速力.
        /// </summary>
        public static string Stats_Speed {
            get {
                return ResourceManager.GetString("Stats_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        public static string Stats_Torpedo {
            get {
                return ResourceManager.GetString("Stats_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これの起動を待っています.
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 準備完了.
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV was unable to check for updates!.
        /// </summary>
        public static string Updater_Notification_CheckFailed {
            get {
                return ResourceManager.GetString("Updater_Notification_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of KCV is available! 「v{0}」
        ///Click here to get it..
        /// </summary>
        public static string Updater_Notification_NewAppVersion {
            get {
                return ResourceManager.GetString("Updater_Notification_NewAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater.
        /// </summary>
        public static string Updater_Notification_Title {
            get {
                return ResourceManager.GetString("Updater_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCV was unable to download the translations!.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Fail {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations are already up-to-date.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Same {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation files have been updated!.
        /// </summary>
        public static string Updater_Notification_TransUpdate_Success {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム {0} % はサポートされていません。.
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズームに失敗しました: {0}.
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム画面の表示サイズ.
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲーム画面の表示サイズを調整.
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
