//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 前のページに戻る 的本地化字符串。
        /// </summary>
        public static string Browser_GoBack {
            get {
                return ResourceManager.GetString("Browser_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次のページに進む 的本地化字符串。
        /// </summary>
        public static string Browser_GoForward {
            get {
                return ResourceManager.GetString("Browser_GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 このページを再読み込む 的本地化字符串。
        /// </summary>
        public static string Browser_ReNavigate {
            get {
                return ResourceManager.GetString("Browser_ReNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL を入力し、Enter キーで移動します。 的本地化字符串。
        /// </summary>
        public static string Browser_URLTip {
            get {
                return ResourceManager.GetString("Browser_URLTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※近日実装予定 的本地化字符串。
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知しない 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (未実装) 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知設定 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Windows 8 以降) 的本地化字符串。
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘 的本地化字符串。
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一覧を生成しています... 的本地化字符串。
        /// </summary>
        public static string CommonCatalog_GeneratingList {
            get {
                return ResourceManager.GetString("CommonCatalog_GeneratingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示の更新 的本地化字符串。
        /// </summary>
        public static string CommonCatalog_Refresh {
            get {
                return ResourceManager.GetString("CommonCatalog_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 これはテスト通知です。 的本地化字符串。
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テスト 的本地化字符串。
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造ドック 的本地化字符串。
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成！ 的本地化字符串。
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造中の艦名をネタバレする 的本地化字符串。
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示設定 的本地化字符串。
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックされています 的本地化字符串。
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工廠第 {0} ドックでの{1}の建造が完了しました。 的本地化字符串。
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了 的本地化字符串。
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドックごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造中の艦 的本地化字符串。
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成時刻 的本地化字符串。
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了まで 的本地化字符串。
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未使用 的本地化字符串。
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征 的本地化字符串。
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征に出ていません。 的本地化字符串。
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「{0}」が遠征から帰投しました。 的本地化字符串。
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征完了 的本地化字符串。
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征帰投時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊ごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終了時刻 的本地化字符串。
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊帰投まで 的本地化字符串。
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空戦力 的本地化字符串。
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レベル 的本地化字符串。
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低速艦隊 的本地化字符串。
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合計 的本地化字符串。
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵能力 的本地化字符串。
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司令部 的本地化字符串。
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修資材: 的本地化字符串。
        /// </summary>
        public static string Homeport_ImprovementMaterial {
            get {
                return ResourceManager.GetString("Homeport_ImprovementMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速建造材: 的本地化字符串。
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速修復材: 的本地化字符串。
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保有装備: 的本地化字符串。
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属艦娘: 的本地化字符串。
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 情報 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 総合 的本地化字符串。
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 この艦隊は遠征中です。 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  完了時刻: 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  帰投まで: 的本地化字符串。
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss} 的本地化字符串。
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に入渠中の艦娘がいます。 的本地化字符串。
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労中の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に{0}がいます。 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃可能！ 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未補給の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再出撃までの目安:  的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ・ 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中破以上の艦娘 的本地化字符串。
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} が大破しています 的本地化字符串。
        /// </summary>
        public static string Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破警告 的本地化字符串。
        /// </summary>
        public static string Notifications_CriticalCondition_Title {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労回復完了 的本地化字符串。
        /// </summary>
        public static string Notifications_MoraleRestored {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「{0}」に編成されている艦娘の疲労が回復しました。 的本地化字符串。
        /// </summary>
        public static string Notifications_MoraleRestored_Details {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データ 的本地化字符串。
        /// </summary>
        public static string Overview_Data {
            get {
                return ResourceManager.GetString("Overview_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備一覧 的本地化字符串。
        /// </summary>
        public static string Overview_EquipmentList {
            get {
                return ResourceManager.GetString("Overview_EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘一覧 的本地化字符串。
        /// </summary>
        public static string Overview_ShipList {
            get {
                return ResourceManager.GetString("Overview_ShipList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務画面の全ページにアクセスしてください。 的本地化字符串。
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  50 %  的本地化字符串。
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  80 %  的本地化字符串。
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  完了  的本地化字符串。
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (未取得の任務) 的本地化字符串。
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任務 的本地化字符串。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在遂行中の任務 的本地化字符串。
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デイリー任務 的本地化字符串。
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 マンスリー任務 的本地化字符串。
        /// </summary>
        public static string Quests_Monthly {
            get {
                return ResourceManager.GetString("Quests_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 発生中の任務はありません 的本地化字符串。
        /// </summary>
        public static string Quests_NoQuest {
            get {
                return ResourceManager.GetString("Quests_NoQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。 的本地化字符串。
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。 的本地化字符串。
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィークリー任務 的本地化字符串。
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大将 的本地化字符串。
        /// </summary>
        public static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大佐 的本地化字符串。
        /// </summary>
        public static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中佐 的本地化字符串。
        /// </summary>
        public static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中堅少佐 的本地化字符串。
        /// </summary>
        public static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 少佐 的本地化字符串。
        /// </summary>
        public static string Rank_Lieutenant_Commander {
            get {
                return ResourceManager.GetString("Rank_Lieutenant_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元帥 的本地化字符串。
        /// </summary>
        public static string Rank_Marshal_Admiral {
            get {
                return ResourceManager.GetString("Rank_Marshal_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新米中佐 的本地化字符串。
        /// </summary>
        public static string Rank_Novice_Commander {
            get {
                return ResourceManager.GetString("Rank_Novice_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新米少佐 的本地化字符串。
        /// </summary>
        public static string Rank_Novice_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Novice_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 少将 的本地化字符串。
        /// </summary>
        public static string Rank_Rear_Admiral {
            get {
                return ResourceManager.GetString("Rank_Rear_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中将 的本地化字符串。
        /// </summary>
        public static string Rank_Vice_Admiral {
            get {
                return ResourceManager.GetString("Rank_Vice_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠ドック 的本地化字符串。
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックされています 的本地化字符串。
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠第 {0} ドックでの「{1}」の整備が完了しました。 的本地化字符串。
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了 的本地化字符串。
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了時に通知を表示する 的本地化字符串。
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドックごとに個別に設定する 的本地化字符串。
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠中の艦 的本地化字符串。
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完了時刻 的本地化字符串。
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整備完了まで 的本地化字符串。
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未使用 的本地化字符串。
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットの保存に失敗しました:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットを保存しました:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設定 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム画面を  的本地化字符串。
        /// </summary>
        public static string Settings_Browser_ResetZoom_Pre {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoom_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % に戻す 的本地化字符串。
        /// </summary>
        public static string Settings_Browser_ResetZoom_Suf {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoom_Suf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (誤ってズームしたとき用) 的本地化字符串。
        /// </summary>
        public static string Settings_Browser_ResetZoomDescription {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ上部のボタンでゲーム画面 (Internet Explorer) の表示サイズを変更できます。スクリーンショットは常に 100 % のサイズで撮影され、表示サイズ設定の影響を受けません。 的本地化字符串。
        /// </summary>
        public static string Settings_Browser_ZoomDescription {
            get {
                return ResourceManager.GetString("Settings_Browser_ZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブラウザー操作 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム倍率を 100 % に戻す 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (表示) 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※ゲームのページから移動します。ご注意ください 的本地化字符串。
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知音を設定 的本地化字符串。
        /// </summary>
        public static string Settings_CustomSound {
            get {
                return ResourceManager.GetString("Settings_CustomSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリューム 的本地化字符串。
        /// </summary>
        public static string Settings_CustomSound_Volume {
            get {
                return ResourceManager.GetString("Settings_CustomSound_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示設定 的本地化字符串。
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        public static string Settings_Flash {
            get {
                return ResourceManager.GetString("Settings_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This works with DMM.com. OSAPI, and API links now!
        ///[You must reload the game for the changes to take affect.] 的本地化字符串。
        /// </summary>
        public static string Settings_Flash_Message {
            get {
                return ResourceManager.GetString("Settings_Flash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Flash Quality: 的本地化字符串。
        /// </summary>
        public static string Settings_Flash_Quality {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best: Anti-Aliasing enabled on all images (Slowest)
        ///High: Default.
        ///Auto-High: Automatically lowers quality when needed.
        ///Medium: Average Performance
        ///AutoLow: Will emphasize speed when needed
        ///Low: Performance over quality. Ugliest setting. 的本地化字符串。
        /// </summary>
        public static string Settings_Flash_Quality_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Flash Window: 的本地化字符串。
        /// </summary>
        public static string Settings_Flash_Window {
            get {
                return ResourceManager.GetString("Settings_Flash_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opaque: Default (Old IE has no HW accel)
        ///Direct: Fastest rendering speed (HW accel)
        ///GPU: Slow! GPU optimization for tablets. 的本地化字符串。
        /// </summary>
        public static string Settings_Flash_Window_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Window_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログ 的本地化字符串。
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドロップ・建造・開発ログを記録する 的本地化字符串。
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信設定 的本地化字符串。
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 パスワード 的本地化字符串。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Password {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシ サーバーにユーザー名とパスワードが必要 的本地化字符串。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Required {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ユーザー名 的本地化字符串。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Username {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知設定 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下のプラグインを使用して通知されます。 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_ActiveNotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_ActiveNotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知を早める： 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これ本体の仕様により、最大 1 分間短縮できます。サーバー時刻とのずれを加味し、40 ～ 50 秒に設定することを推奨します。 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Seconds {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造完了時に通知する 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_Construction_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Construction_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破艦がいる場合に通知する 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Settings_Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征帰投時に通知する 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_Expeditions_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Expeditions_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に編成されている艦娘の疲労が回復したら通知する 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に編成されているすべて艦娘のコンディション値が上記の値以上になったときに通知されます。コンディション値は 3 分間で 3 ずつ回復しますが、KanColleViewer 実装の仕様により、通知タイミングは数秒 ～ 最大 3 分程度遅れる可能性があること予めご了承ください。 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※[動作設定] &gt; [出撃コンディション] から設定できます。 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Reference {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再出撃可能とするコンディション値 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Threshold {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知設定 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_NotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_NotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠完了時に通知する 的本地化字符串。
        /// </summary>
        public static string Settings_Notifications_Repair_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Repair_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 動作設定 的本地化字符串。
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦上偵察機 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彩雲、二式艦上偵察機 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (偵察機 × 2) + (電探) + √(装備込みの艦隊索敵値合計 - 偵察機 - 電探) 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_New {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備による索敵値が重要とされる場合の計算方法 (推定) 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_New_Desc {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 偵察機 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_Recon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水上爆撃機 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瑞雲、瑞雲(六三四空)、試製晴嵐 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水上偵察機 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零式水上偵察機、零式水上観測機、九八式水上偵察機(夜偵) 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘と装備の索敵値の単純な合計 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_Simple {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KanColleViewer での従来の計算方法 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_Simple_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊の索敵値の算出に使用する計算式は、以下を使用する 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoS_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵値計算 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_LoSCalculation {
            get {
                return ResourceManager.GetString("Settings_Operation_LoSCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃コンディション 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_SortieCondition {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ※通常は、間宮アイコンが消灯する 40 か、自然回復上限の 49 に設定します。 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_SortieCondition_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊内の全艦のコンディションが次の数値以上になったとき、出撃可能と判断する 的本地化字符串。
        /// </summary>
        public static string Settings_Operation_SortieCondition_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 その他 的本地化字符串。
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロキシ設定 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信にプロキシ サーバーを使用する 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL 接続時もプロキシサーバーを使用する 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サーバー 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポート 的本地化字符串。
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショット 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スクリーンショットの保存先を指定 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存先 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存先フォルダーのパス 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画像形式 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フォルダーを開く 的本地化字符串。
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translations 的本地化字符串。
        /// </summary>
        public static string Settings_Translations {
            get {
                return ResourceManager.GetString("Settings_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append untranslated items to the translation files? 的本地化字符串。
        /// </summary>
        public static string Settings_Translations_Add_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Add_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate game items, ships, and quests to selected language? 的本地化字符串。
        /// </summary>
        public static string Settings_Translations_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI設定 的本地化字符串。
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アイコンを利用する 的本地化字符串。
        /// </summary>
        public static string Settings_UI_Icon {
            get {
                return ResourceManager.GetString("Settings_UI_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデート 的本地化字符串。
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時に言語ファイルをアップデート 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_AutoUpdateTrans {
            get {
                return ResourceManager.GetString("Settings_Updates_AutoUpdateTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートの有無をチェックしています 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_CheckUpdateButn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdateButn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートチェック 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートがあるかどうかチェックします 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在のバージョン 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_CurrentVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強制的に更新 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新の有無に関係なくすべての言語ファイルをダウンロードします 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配布サイトに行く 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_GetKCVBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版の配布サイトを開きます 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_GetKCVBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新バージョン 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_OnlineVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_OnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデート設定 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_Option {
            get {
                return ResourceManager.GetString("Settings_Updates_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起動時にアップデートチェック 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語ファイルをダウンロード 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートがある場合は言語ファイルをダウンロードします 的本地化字符串。
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 バージョン情報 的本地化字符串。
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ設定 的本地化字符串。
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウを常に最前面に表示する 的本地化字符串。
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ操作 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウをモニターの左端に寄せる 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 インチタブレット (800 x 1280) 用 的本地化字符串。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠: {0} 的本地化字符串。
        /// </summary>
        public static string Ship_RepairDockToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairDockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 施設: {0} 的本地化字符串。
        /// </summary>
        public static string Ship_RepairFacilityToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairFacilityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠中 的本地化字符串。
        /// </summary>
        public static string Ship_Repairing {
            get {
                return ResourceManager.GetString("Ship_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべて 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_All {
            get {
                return ResourceManager.GetString("ShipCatalog_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対空 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_AntiAir {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_AntiSub {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装甲 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Armor {
            get {
                return ResourceManager.GetString("ShipCatalog_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Equips {
            get {
                return ResourceManager.GetString("ShipCatalog_Equips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回避 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Evasion {
            get {
                return ResourceManager.GetString("ShipCatalog_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征中の艦を除外する 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ExcludeShipOnExpedition {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShipOnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦種を除く！ 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ExcludeShiptype {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShiptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Expedition {
            get {
                return ResourceManager.GetString("ShipCatalog_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高速 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Fast {
            get {
                return ResourceManager.GetString("ShipCatalog_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フィルター設定 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_FilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火力 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Firepower {
            get {
                return ResourceManager.GetString("ShipCatalog_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レベル 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Level {
            get {
                return ResourceManager.GetString("ShipCatalog_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv.1 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Level1 {
            get {
                return ResourceManager.GetString("ShipCatalog_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv.2 以上 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Level2Up {
            get {
                return ResourceManager.GetString("ShipCatalog_Level2Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロック 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Lock {
            get {
                return ResourceManager.GetString("ShipCatalog_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックしている 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Locked {
            get {
                return ResourceManager.GetString("ShipCatalog_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_LoS {
            get {
                return ResourceManager.GetString("ShipCatalog_LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Luck {
            get {
                return ResourceManager.GetString("ShipCatalog_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 近代化改修 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Modernization {
            get {
                return ResourceManager.GetString("ShipCatalog_Modernization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修完了 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ModernizationComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改修未完 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ModernizationIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦名 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Name {
            get {
                return ResourceManager.GetString("ShipCatalog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AL 作戦参加済み 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Operation_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MI 作戦参加済み 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Operation_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作戦出撃なし 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Operation_NeitherALnorMI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_NeitherALnorMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改造 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Remodel {
            get {
                return ResourceManager.GetString("ShipCatalog_Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改造完了 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_RemodelComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改造未完 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_RemodelIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フィルター設定リセット 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ResetFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_ResetFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フィルター設定を保存 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_SaveFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_SaveFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべて選択 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_SelectAll {
            get {
                return ResourceManager.GetString("ShipCatalog_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦種 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ShipType {
            get {
                return ResourceManager.GetString("ShipCatalog_ShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ステータスをすべて表示 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_ShowAdditionalShipStats {
            get {
                return ResourceManager.GetString("ShipCatalog_ShowAdditionalShipStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低速 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Slow {
            get {
                return ResourceManager.GetString("ShipCatalog_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃海域 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_SortieWaters {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AL 作戦 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_SortieWaters_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MI 作戦 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_SortieWaters_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速力 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Speed {
            get {
                return ResourceManager.GetString("ShipCatalog_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷装 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Torpedo {
            get {
                return ResourceManager.GetString("ShipCatalog_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ロックしていない 的本地化字符串。
        /// </summary>
        public static string ShipCatalog_Unlocked {
            get {
                return ResourceManager.GetString("ShipCatalog_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工廠 的本地化字符串。
        /// </summary>
        public static string Shipyard {
            get {
                return ResourceManager.GetString("Shipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建造 的本地化字符串。
        /// </summary>
        public static string Shipyard_ConstructionDock {
            get {
                return ResourceManager.GetString("Shipyard_ConstructionDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備開発・ドロップ 的本地化字符串。
        /// </summary>
        public static string Shipyard_Development {
            get {
                return ResourceManager.GetString("Shipyard_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失敗 的本地化字符串。
        /// </summary>
        public static string Shipyard_Development_Result_Failure {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結果なし 的本地化字符串。
        /// </summary>
        public static string Shipyard_Development_Result_None {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Shipyard_Development_Result_Success {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ドロップ 的本地化字符串。
        /// </summary>
        public static string Shipyard_Drop {
            get {
                return ResourceManager.GetString("Shipyard_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠 的本地化字符串。
        /// </summary>
        public static string Shipyard_RepairDock {
            get {
                return ResourceManager.GetString("Shipyard_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備名 的本地化字符串。
        /// </summary>
        public static string SlotItemCatalog_EqipName {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EqipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備している艦娘 的本地化字符串。
        /// </summary>
        public static string SlotItemCatalog_EquippedShipGirls {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EquippedShipGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余り 的本地化字符串。
        /// </summary>
        public static string SlotItemCatalog_Extra {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所持数 的本地化字符串。
        /// </summary>
        public static string SlotItemCatalog_Owned {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ステータス 的本地化字符串。
        /// </summary>
        public static string SlotItemCatalog_Stats {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャッシュの削除 的本地化字符串。
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャッシュを削除しました 的本地化字符串。
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。 的本地化字符串。
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クッキーの設定 的本地化字符串。
        /// </summary>
        public static string StartContent_SetRegionCookieButton {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クッキーを設定しました 的本地化字符串。
        /// </summary>
        public static string StartContent_SetRegionCookieMessage {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure DMM.com is set to Japanese (日本語) 的本地化字符串。
        /// </summary>
        public static string StartContent_SetRegionCookieToolTip {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ようこそ 的本地化字符串。
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破した艦娘がいます！！！ 的本地化字符串。
        /// </summary>
        public static string StateDetail_CriticalDamage {
            get {
                return ResourceManager.GetString("StateDetail_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に艦娘が編成されていません。 的本地化字符串。
        /// </summary>
        public static string StateDetail_EmptyFleet {
            get {
                return ResourceManager.GetString("StateDetail_EmptyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃可能！ 的本地化字符串。
        /// </summary>
        public static string StateDetail_IsReady {
            get {
                return ResourceManager.GetString("StateDetail_IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労回復済み 的本地化字符串。
        /// </summary>
        public static string StateDetail_MoraleRecovering {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労回復まで 的本地化字符串。
        /// </summary>
        public static string StateDetail_MoraleRecoveryTimer {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecoveryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征中 的本地化字符串。
        /// </summary>
        public static string StateDetail_OnExpedition {
            get {
                return ResourceManager.GetString("StateDetail_OnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊は出撃中です！ 的本地化字符串。
        /// </summary>
        public static string StateDetail_OnSortie {
            get {
                return ResourceManager.GetString("StateDetail_OnSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦娘入渠まで 的本地化字符串。
        /// </summary>
        public static string StateDetail_Repairing {
            get {
                return ResourceManager.GetString("StateDetail_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦隊に未補給の艦娘がいます。 的本地化字符串。
        /// </summary>
        public static string StateDetail_ShortSupply {
            get {
                return ResourceManager.GetString("StateDetail_ShortSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命中 的本地化字符串。
        /// </summary>
        public static string Stats_Accuracy {
            get {
                return ResourceManager.GetString("Stats_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対空 的本地化字符串。
        /// </summary>
        public static string Stats_AntiAir {
            get {
                return ResourceManager.GetString("Stats_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜 的本地化字符串。
        /// </summary>
        public static string Stats_AntiSub {
            get {
                return ResourceManager.GetString("Stats_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装甲 的本地化字符串。
        /// </summary>
        public static string Stats_Armor {
            get {
                return ResourceManager.GetString("Stats_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 射程 的本地化字符串。
        /// </summary>
        public static string Stats_AttackRange {
            get {
                return ResourceManager.GetString("Stats_AttackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爆装 的本地化字符串。
        /// </summary>
        public static string Stats_DiveBomb {
            get {
                return ResourceManager.GetString("Stats_DiveBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回避 的本地化字符串。
        /// </summary>
        public static string Stats_Evasion {
            get {
                return ResourceManager.GetString("Stats_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火力 的本地化字符串。
        /// </summary>
        public static string Stats_Firepower {
            get {
                return ResourceManager.GetString("Stats_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耐久 的本地化字符串。
        /// </summary>
        public static string Stats_Health {
            get {
                return ResourceManager.GetString("Stats_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 運 的本地化字符串。
        /// </summary>
        public static string Stats_Luck {
            get {
                return ResourceManager.GetString("Stats_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵 的本地化字符串。
        /// </summary>
        public static string Stats_SightRange {
            get {
                return ResourceManager.GetString("Stats_SightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速力 的本地化字符串。
        /// </summary>
        public static string Stats_Speed {
            get {
                return ResourceManager.GetString("Stats_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷装 的本地化字符串。
        /// </summary>
        public static string Stats_Torpedo {
            get {
                return ResourceManager.GetString("Stats_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これの起動を待っています 的本地化字符串。
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 準備完了 的本地化字符串。
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツール 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデートチェックに失敗しました 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_CheckFailed {
            get {
                return ResourceManager.GetString("Updater_Notification_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新しいバージョンがあります 「v{0}」
        ///ここをクリックするとサイトが開きます 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_NewAppVersion {
            get {
                return ResourceManager.GetString("Updater_Notification_NewAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデート 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_Title {
            get {
                return ResourceManager.GetString("Updater_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語ファイルのダウンロードに失敗 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Fail {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語ファイルは既に最新版です 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Same {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 言語ファイルをアップデートしました 的本地化字符串。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Success {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズーム {0} % はサポートされていません。 的本地化字符串。
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ズームに失敗しました: {0} 的本地化字符串。
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム画面の表示サイズ 的本地化字符串。
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ゲーム画面の表示サイズを調整 的本地化字符串。
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
